name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Most 3 recent versions and highest of the last 2 minor versions
        # list from - https://github.com/meetecho/janus-gateway/blob/0.x/CHANGELOG.md
        janus_version: ["0.10.10", "0.11.8", "0.12.2", "0.12.3", "0.12.4"]
        build_arg_type: ["default", "full"]
        include:
          - build_arg_type: "default"
            build_args: ""
          - build_arg_type: "full"
            build_args: "--build-arg JANUS_WITH_POSTPROCESSING=1 \
              --build-arg JANUS_WITH_BORINGSSL=0 \
              --build-arg JANUS_WITH_DOCS=0 \
              --build-arg JANUS_WITH_REST=1 \
              --build-arg JANUS_WITH_DATACHANNELS=1 \
              --build-arg JANUS_WITH_WEBSOCKETS=1 \
              --build-arg JANUS_WITH_MQTT=1 \
              --build-arg JANUS_WITH_PFUNIX=1 \
              --build-arg JANUS_WITH_RABBITMQ=0 \
              --build-arg JANUS_WITH_FREESWITCH_PATCH=0"

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image with Janus version
      id: build
      run: docker build --build-arg JANUS_VERSION=${{ matrix.janus_version }} ${{ matrix.build_args }} . --file Dockerfile

    - name: Notify failure
      if: steps.build.outcome != 'success'
      run: exit 1
